[package]
name = "mia/slap-battles-plugins"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Jian = "miagobble/jian@0.1.1"
Seam = "miagobble/seam@0.5.6"